/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fp.tdtu.finalproject;

import java.awt.Color;

/**
 *
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        livingroom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bathroom = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bedroom = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kitchen = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        livingroombg = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btncleanrobotliving = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bathroombg = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bntWashingMachine = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bedroombg = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btncleanrobotbed = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        kitchenbg = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnDishWasher = new javax.swing.JButton();
        btnMicrowaveOver = new javax.swing.JButton();
        btnOven = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        btnAdd1.setText("add");
        btnAdd1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), null, null));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));

        livingroom.setBackground(java.awt.Color.white);
        livingroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                livingroomMouseClicked(evt);
            }
        });

        jLabel1.setText("Living Room");

        javax.swing.GroupLayout livingroomLayout = new javax.swing.GroupLayout(livingroom);
        livingroom.setLayout(livingroomLayout);
        livingroomLayout.setHorizontalGroup(
            livingroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, livingroomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
        );
        livingroomLayout.setVerticalGroup(
            livingroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, livingroomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        bathroom.setBackground(java.awt.Color.white);
        bathroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bathroomMouseClicked(evt);
            }
        });

        jLabel2.setText("Bathroom");

        javax.swing.GroupLayout bathroomLayout = new javax.swing.GroupLayout(bathroom);
        bathroom.setLayout(bathroomLayout);
        bathroomLayout.setHorizontalGroup(
            bathroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bathroomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(63, 63, 63))
        );
        bathroomLayout.setVerticalGroup(
            bathroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bathroomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        bedroom.setBackground(java.awt.Color.white);
        bedroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bedroomMouseClicked(evt);
            }
        });

        jLabel3.setText("Bedroom");

        javax.swing.GroupLayout bedroomLayout = new javax.swing.GroupLayout(bedroom);
        bedroom.setLayout(bedroomLayout);
        bedroomLayout.setHorizontalGroup(
            bedroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bedroomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(66, 66, 66))
        );
        bedroomLayout.setVerticalGroup(
            bedroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bedroomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        kitchen.setBackground(java.awt.Color.white);
        kitchen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitchenMouseClicked(evt);
            }
        });

        jLabel4.setText("Kitchen");

        javax.swing.GroupLayout kitchenLayout = new javax.swing.GroupLayout(kitchen);
        kitchen.setLayout(kitchenLayout);
        kitchenLayout.setHorizontalGroup(
            kitchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitchenLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kitchenLayout.setVerticalGroup(
            kitchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitchenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MY SMART HOME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bathroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bedroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kitchen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(livingroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(livingroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bathroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bedroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kitchen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        livingroombg.setBackground(new java.awt.Color(255, 255, 255));
        livingroombg.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        livingroombg.add(jPanel3);
        jPanel3.setBounds(210, 90, 20, 10);

        btncleanrobotliving.setText("Cleaner Robot");
        btncleanrobotliving.setActionCommand("Cleaner Robot");
        btncleanrobotliving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncleanrobotlivingActionPerformed(evt);
            }
        });
        livingroombg.add(btncleanrobotliving);
        btncleanrobotliving.setBounds(70, 30, 180, 80);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Trong Dai\\Documents\\NetBeansProjects\\finalProject\\src\\main\\java\\img\\livingroom.jpg")); // NOI18N
        livingroombg.add(jLabel6);
        jLabel6.setBounds(0, 0, 530, 290);

        jPanel2.add(livingroombg);

        bathroombg.setBackground(new java.awt.Color(255, 255, 255));
        bathroombg.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        bathroombg.add(jPanel4);
        jPanel4.setBounds(210, 100, 20, 10);

        bntWashingMachine.setText(" Washing Machine");
        bntWashingMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntWashingMachineActionPerformed(evt);
            }
        });
        bathroombg.add(bntWashingMachine);
        bntWashingMachine.setBounds(70, 40, 180, 80);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Trong Dai\\Documents\\NetBeansProjects\\finalProject\\src\\main\\java\\img\\bathroom.jpg")); // NOI18N
        jLabel7.setToolTipText("");
        bathroombg.add(jLabel7);
        jLabel7.setBounds(0, 0, 530, 280);

        jPanel2.add(bathroombg);

        bedroombg.setBackground(new java.awt.Color(255, 255, 255));
        bedroombg.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        bedroombg.add(jPanel5);
        jPanel5.setBounds(220, 100, 20, 10);

        btncleanrobotbed.setText("Cleaner Robot");
        btncleanrobotbed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncleanrobotbedActionPerformed(evt);
            }
        });
        bedroombg.add(btncleanrobotbed);
        btncleanrobotbed.setBounds(50, 40, 210, 80);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Trong Dai\\Documents\\NetBeansProjects\\finalProject\\src\\main\\java\\img\\bedroom.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        bedroombg.add(jLabel8);
        jLabel8.setBounds(0, 0, 530, 280);

        jPanel2.add(bedroombg);

        kitchenbg.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        kitchenbg.add(jPanel6);
        jPanel6.setBounds(200, 100, 20, 10);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        kitchenbg.add(jPanel7);
        jPanel7.setBounds(430, 100, 20, 10);

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        kitchenbg.add(jPanel8);
        jPanel8.setBounds(200, 210, 20, 10);

        btnDishWasher.setText("Dish washer");
        btnDishWasher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDishWasherActionPerformed(evt);
            }
        });
        kitchenbg.add(btnDishWasher);
        btnDishWasher.setBounds(50, 40, 180, 80);

        btnMicrowaveOver.setText("Microwave Oven");
        btnMicrowaveOver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMicrowaveOverActionPerformed(evt);
            }
        });
        kitchenbg.add(btnMicrowaveOver);
        btnMicrowaveOver.setBounds(270, 40, 190, 80);

        btnOven.setText("Oven");
        btnOven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOvenActionPerformed(evt);
            }
        });
        kitchenbg.add(btnOven);
        btnOven.setBounds(50, 150, 180, 80);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Trong Dai\\Documents\\NetBeansProjects\\finalProject\\src\\main\\java\\img\\kitchen.jpg")); // NOI18N
        kitchenbg.add(jLabel9);
        jLabel9.setBounds(0, 0, 530, 280);

        jPanel2.add(kitchenbg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void livingroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livingroomMouseClicked
        livingroombg.setVisible(true);
        bathroombg.setVisible(false);
        bedroombg.setVisible(false);
        kitchenbg.setVisible(false);
        
        livingroom.setBackground(Color.gray);
        bathroom.setBackground(Color.white);
        bedroom.setBackground(Color.white);
        kitchen.setBackground(Color.white);
    }//GEN-LAST:event_livingroomMouseClicked

    private void bathroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bathroomMouseClicked
        livingroombg.setVisible(false);
        bathroombg.setVisible(true);
        bedroombg.setVisible(false);
        kitchenbg.setVisible(false);
        
        livingroom.setBackground(Color.white);
        bathroom.setBackground(Color.gray);
        bedroom.setBackground(Color.white);
        kitchen.setBackground(Color.white);
    }//GEN-LAST:event_bathroomMouseClicked

    private void bedroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bedroomMouseClicked
        livingroombg.setVisible(false);
        bathroombg.setVisible(false);
        bedroombg.setVisible(true);
        kitchenbg.setVisible(false);
        
        livingroom.setBackground(Color.white);
        bathroom.setBackground(Color.white);
        bedroom.setBackground(Color.gray);
        kitchen.setBackground(Color.white);
    }//GEN-LAST:event_bedroomMouseClicked

    private void kitchenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitchenMouseClicked
        livingroombg.setVisible(false);
        bathroombg.setVisible(false);
        bedroombg.setVisible(false);
        kitchenbg.setVisible(true);
        
        livingroom.setBackground(Color.white);
        bathroom.setBackground(Color.white);
        bedroom.setBackground(Color.white);
        kitchen.setBackground(Color.gray);
    }//GEN-LAST:event_kitchenMouseClicked

    private void btncleanrobotlivingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncleanrobotlivingActionPerformed
        CleanRobotRemoteLivingRoom crlr = new CleanRobotRemoteLivingRoom ();
        crlr.setVisible(true);
        
    }//GEN-LAST:event_btncleanrobotlivingActionPerformed

    private void btncleanrobotbedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncleanrobotbedActionPerformed
       CleanRobotRemoteBedroom crb = new CleanRobotRemoteBedroom();
       crb.setVisible(true);
    }//GEN-LAST:event_btncleanrobotbedActionPerformed

    private void bntWashingMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntWashingMachineActionPerformed
        WashingMachine wm = new WashingMachine();
        wm.setVisible(true);
    }//GEN-LAST:event_bntWashingMachineActionPerformed

    private void btnDishWasherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDishWasherActionPerformed
        DishWasher dw = new DishWasher();
        dw.setVisible(true);
    }//GEN-LAST:event_btnDishWasherActionPerformed

    private void btnOvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOvenActionPerformed
        Oven o = new Oven();
        o.setVisible(true);
    }//GEN-LAST:event_btnOvenActionPerformed

    private void btnMicrowaveOverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMicrowaveOverActionPerformed
        MicrowaveOven mo = new MicrowaveOven();
        mo.setVisible(true);
    }//GEN-LAST:event_btnMicrowaveOverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bathroom;
    private javax.swing.JPanel bathroombg;
    private javax.swing.JPanel bedroom;
    private javax.swing.JPanel bedroombg;
    private javax.swing.JButton bntWashingMachine;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnDishWasher;
    private javax.swing.JButton btnMicrowaveOver;
    private javax.swing.JButton btnOven;
    private javax.swing.JButton btncleanrobotbed;
    private javax.swing.JButton btncleanrobotliving;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel kitchen;
    private javax.swing.JPanel kitchenbg;
    private javax.swing.JPanel livingroom;
    private javax.swing.JPanel livingroombg;
    // End of variables declaration//GEN-END:variables
}
